### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by tinyCtim**

### CODE REVIEW

**Comment by tgibson37** [comment]
OK, this is what I was looking for, the dialog box. Joint study issue(s): Can we each do a setting somewhere that gives us email notice of dialog, kind-a like face book? And here is a link to the page I am writing from...   [https://github.com/tgibson37/tiny-c/pull/2](url).   That's nice.
I have a big green button "Merge pull request" which will merge your work into mine. How do I examine your work before doing the merge? Can you do that merge? (I assume not.) Finnaly I have two buttons below, Close and comment (grey), and Comment (green). I am poking the green one now...

**Comment by tgibson37** [comment]
The dialog window emptied, so it is going somewhere, hopefully to you. The Close and comment button changed to Close pull request, but now its Close and comment because I'm typing again.

**Comment by tinyCtim** [comment]
OK. I have found the page where you have entered the above comments. Did you get my os.tc to go to your Experimental when you pushed the "Merge pull request" button?

BTW, this os.tc is not that big a deal. Being a .tc file it's not a suggestion for interpreter modification. It's just a simple function that might be useful in a system or personal library. Am adding it to my Experimental simply to learn how we can learn how collaborating works. Not unlike your snow.tc.

**Comment by tgibson37** [comment]
Interesting. I had not merged when I went for lunch. When I got back you had closed it. No merge button, but near the bottom was a reopen button. Clicked that, merged, All seems happy. There is even a revert button. But instead I will go to tiny-c and I expect to find os.tc there.

**Pull request merged**
