### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by tinyCtim**
Please consider these changes.
A minor change to tc.h
A couple of new machine calls. Implementation of user machine calls.
Several sample tinyC programs that use these features.
A personal library that is #included in the sample programs.

### CODE REVIEW

**Comment by tinyCtim** [comment]
All your comments are excellent. I have been struggling with this Windows/Linux conflict for months. Gotta somehow wrap the C code w/ if Windows do this if Linux do this. 

No, I put my samples in the "root." Should have put them in Sample.

I don't see MCs changing too frequently. But you have a point. Maybe we should consider tc.prop. For me, it's beginning to look like an ".ini" file and not just a place the interpreter visits at startup to do its allocating. Adding to my Operating System idea (OS= line) we could have a MC= line. No compilation needed. This is minor but if we go with extending the role tc.prop will play, maybe we should stick w/ your original format spec, i.e.

KEYWORD            value
KEYWORD            value

I think lrblib.tc would work.

And yes, I currently have lots of std lib in my personal lib. This because I've been trying to write programs that require only my personal lib and this forced me to borrow from the std lib. I will remove all dups and #include both libs now.

**Comment by tgibson37** [comment]
OK, got this one. Learning department: At the near top of this page is Conversation,checks,commits,files changed. THOSE ARE TABS! I'm typing this from the bottom of the conversation tabs. 
Comments department: YES on MC issue. The platform.c code is where I will put this. It already has the if windows else linux separation. I'll do that and you do the personal lib stuff. 
Put version in your personal, but you have me thinking about a standard version stamp. Would a date/time stamp be ok? Linux has a lib fcn that returns, e.g. "18052018". Maybe there is a compile time macro that returns the same. Let me research that. 
One other thought. Pull requests are cheap. Best to use them issue-by-issue. Nothing wrong with a stack of them like my work inbox back when I had a paper inbox. That way the good stuff slides into a release and isn't delayed by an item needing time.
Enuf for now! My beer buddies await!

**Comment by tinyCtim** [comment]
Hope this all works. Let me know.

**Comment by tgibson37** [comment]
I'm back from Sat AM meeting. Looks like good progress. What I would like to do is look over each commit, and run the regression and dialog tests. But I am offered one "Merge pull request" button. So here are my thoughts. Let me know if this works for you ...
1 -- do the merge. It goes into Base which I assume is master.
2 -- Examine what happened. 
3 -- check out whichever branch your work is in, probably master
4 -- run my examination locally
5 -- communicate any issues

**Comment by tinyCtim** [comment]
All my stuff was put in my experimental. I assume what your recent  merge did was put my stuff in your experimental. After you test get back to me with your decisions on changes etc. and then we should decide what if anything should be put into master.

**Comment by tgibson37** [comment]
OK, got your "hope this all works". Here goes...
1 -- done, 
2 -- ???  Need to fetch(?) some remote branch. Or maybe diff?   --   stay tuned.

**Pull request merged**
